server:
    port: 9129
spring:
    application:
        name: soconfig-server
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:mydb;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
        username: sa
        password:
    sql:
        init:
            #            schema-locations: classpath:db/schema.sql
            mode: always
            schema-locations:
                    - classpath:db/schema.sql
            data-locations:
                    - classpath:db/data.sql
    h2:
        console:
          enabled: true
          path: /h2-console
          settings:
              web-allow-others: true
logging:
    level:
        root: info
        org.springframework: info
mybatis:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



